'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:4.0.30319.1
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'このクラスは StronglyTypedResourceBuilder クラスが ResGen
    'または Visual Studio のようなツールを使用して自動生成されました。
    'メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    'ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    '''<summary>
    '''  ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Tween.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        '''  現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  (新規タブ) に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property AddNewTabText1() As String
            Get
                Return ResourceManager.GetString("AddNewTabText1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  名前 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property AddNewTabText2() As String
            Get
                Return ResourceManager.GetString("AddNewTabText2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  投稿 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property AddNewTabText3() As String
            Get
                Return ResourceManager.GetString("AddNewTabText3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  取得日時 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property AddNewTabText4() As String
            Get
                Return ResourceManager.GetString("AddNewTabText4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  日時 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property AddNewTabText4_2() As String
            Get
                Return ResourceManager.GetString("AddNewTabText4_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  ユーザ名 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property AddNewTabText5() As String
            Get
                Return ResourceManager.GetString("AddNewTabText5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  タブ　&quot;&quot;{0}&quot;&quot;　は既に存在するため、追加できません。別の名前を指定してください。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property AddTabMenuItem_ClickText1() As String
            Get
                Return ResourceManager.GetString("AddTabMenuItem_ClickText1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  タブ追加 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property AddTabMenuItem_ClickText2() As String
            Get
                Return ResourceManager.GetString("AddTabMenuItem_ClickText2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  上限 :  に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ApiInfo1() As String
            Get
                Return ResourceManager.GetString("ApiInfo1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  残数 :  に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ApiInfo2() As String
            Get
                Return ResourceManager.GetString("ApiInfo2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  リセット日時 :  に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ApiInfo3() As String
            Get
                Return ResourceManager.GetString("ApiInfo3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  API情報 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ApiInfo4() As String
            Get
                Return ResourceManager.GetString("ApiInfo4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''   * API情報の取得に失敗 * に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ApiInfo5() As String
            Get
                Return ResourceManager.GetString("ApiInfo5", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property At() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("At", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property AtBlink() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("AtBlink", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property AtRed() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("AtRed", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property AtSmoke() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("AtSmoke", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  認証しました に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property AuthorizeButton_Click1() As String
            Get
                Return ResourceManager.GetString("AuthorizeButton_Click1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  認証できませんでした に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property AuthorizeButton_Click2() As String
            Get
                Return ResourceManager.GetString("AuthorizeButton_Click2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  認証済 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property AuthorizeButton_Click3() As String
            Get
                Return ResourceManager.GetString("AuthorizeButton_Click3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  未認証 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property AuthorizeButton_Click4() As String
            Get
                Return ResourceManager.GetString("AuthorizeButton_Click4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  実行形式ファイル(*.exe)|*.exe|すべてのファイル(*.*)|*.* に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property Button3_ClickText1() As String
            Get
                Return ResourceManager.GetString("Button3_ClickText1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  ブラウザを指定してください に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property Button3_ClickText2() As String
            Get
                Return ResourceManager.GetString("Button3_ClickText2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  このルールを削除してもよろしいですか？{0}   『{1}』 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ButtonDelete_ClickText1() As String
            Get
                Return ResourceManager.GetString("ButtonDelete_ClickText1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  ルール削除確認 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ButtonDelete_ClickText2() As String
            Get
                Return ResourceManager.GetString("ButtonDelete_ClickText2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  ルールを指定してください。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ButtonOK_ClickText1() As String
            Get
                Return ResourceManager.GetString("ButtonOK_ClickText1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  ルールチェック に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ButtonOK_ClickText2() As String
            Get
                Return ResourceManager.GetString("ButtonOK_ClickText2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  正規表現エラー： に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ButtonOK_ClickText3() As String
            Get
                Return ResourceManager.GetString("ButtonOK_ClickText3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  既に存在するルールは追加できません に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ButtonOK_ClickText4() As String
            Get
                Return ResourceManager.GetString("ButtonOK_ClickText4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  更新履歴
        '''
        '''==== Ver 0.8.9.3(2010/05/**)
        ''' * Alt+Shift+R,Ctrl+Qが効かない場合があったバグを修正
        ''' * Replyタブの初期設定での更新間隔を180秒に。バージョンアップの方は手動で調整してください。
        ''' * ユーザー情報ダイアログで自己紹介の部分をhtml化して表示するようにした。サムネイルと右クリックメニュー以外は、@IDやハッシュタグのリンク化など、詳細表示とほぼ同等の機能があります。
        ''' * ユーザー情報ダイアログでクリックしてジャンプできる場所はツールチップでジャンプ先URLを表示するようにした
        ''' * ユーザー情報ダイアログで最新の発言を表示するようにした
        ''' * ユーザー情報ダイアログの発言、自己紹介の各表示エリアで右クリックからコピー・すべて選択ができるようにした
        ''' * 画像サムネイルのSplitterDistanceが復元されないことがあるバグ修正
        ''' * 投稿時に投稿完了を待たないように変更。投稿失敗はメッセージで通知し、リトライ・キャンセルを選べるように。
        ''' * ふぁぼったーのURL変更
        ''' * メニューの「片思いユーザーリスト [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ChangeLog() As String
            Get
                Return ResourceManager.GetString("ChangeLog", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Tween更新確認 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property CheckNewVersionText1() As String
            Get
                Return ResourceManager.GetString("CheckNewVersionText1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  更新版のバージョン取得に失敗しました。しばらく待ってから再度お試しください。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property CheckNewVersionText10() As String
            Get
                Return ResourceManager.GetString("CheckNewVersionText10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Tween更新結果 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property CheckNewVersionText2() As String
            Get
                Return ResourceManager.GetString("CheckNewVersionText2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  新しいバージョン {0} が公開されています。更新しますか？ に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property CheckNewVersionText3() As String
            Get
                Return ResourceManager.GetString("CheckNewVersionText3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  アップデーターのダウンロードに失敗しました。しばらく待ってから再度お試しください。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property CheckNewVersionText4() As String
            Get
                Return ResourceManager.GetString("CheckNewVersionText4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  最新版が公開されていますが、ダウンロードに失敗しました。しばらく待ってから再度お試しください。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property CheckNewVersionText5() As String
            Get
                Return ResourceManager.GetString("CheckNewVersionText5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  新しいバージョンは見つかりません。 {0} が公開されています。強制的に更新しますか？ に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property CheckNewVersionText6() As String
            Get
                Return ResourceManager.GetString("CheckNewVersionText6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  最新版をお使いです。更新の必要はありませんでした。使用中Ver： に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property CheckNewVersionText7() As String
            Get
                Return ResourceManager.GetString("CheckNewVersionText7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  最新Ver： に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property CheckNewVersionText8() As String
            Get
                Return ResourceManager.GetString("CheckNewVersionText8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  バージョンチェック失敗 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property CheckNewVersionText9() As String
            Get
                Return ResourceManager.GetString("CheckNewVersionText9", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  このタブの発言をクリアしてもよろしいですか？{0}（サーバーから発言は削除しません。） に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ClearTabMenuItem_ClickText1() As String
            Get
                Return ResourceManager.GetString("ClearTabMenuItem_ClickText1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  タブクリア確認 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ClearTabMenuItem_ClickText2() As String
            Get
                Return ResourceManager.GetString("ClearTabMenuItem_ClickText2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  無効な日時書式指定文字列です に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property CmbDateTimeFormat_Validating() As String
            Get
                Return ResourceManager.GetString("CmbDateTimeFormat_Validating", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  タイムアウトまでの時間には数値（0～120）を指定してください。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ConnectionTimeOut_ValidatingText1() As String
            Get
                Return ResourceManager.GetString("ConnectionTimeOut_ValidatingText1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  (アイコンが取得できていません) に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ContextMenuStrip3_OpeningText1() As String
            Get
                Return ResourceManager.GetString("ContextMenuStrip3_OpeningText1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  (発言を選択してください) に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ContextMenuStrip3_OpeningText2() As String
            Get
                Return ResourceManager.GetString("ContextMenuStrip3_OpeningText2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  無効な日時書式指定文字列です に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property CreateDateTimeFormatSampleText1() As String
            Get
                Return ResourceManager.GetString("CreateDateTimeFormatSampleText1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  選択しているハッシュタグを削除してもよろしいですか？ に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property DeleteHashtagsMessage1() As String
            Get
                Return ResourceManager.GetString("DeleteHashtagsMessage1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  選択されている自発言(またはDM)を削除してもよろしいですか？{0}注意　：　Twitterサーバからも削除されます！{0}　タブからIDを削除する場合は、「IDを移動」を使ってください。{0}　タブを削除する場合は、「タブを削除」を使ってください。{0}{0}削除処理を中止するには、「キャンセル」ボタンを押してください。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property DeleteStripMenuItem_ClickText1() As String
            Get
                Return ResourceManager.GetString("DeleteStripMenuItem_ClickText1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  削除確認 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property DeleteStripMenuItem_ClickText2() As String
            Get
                Return ResourceManager.GetString("DeleteStripMenuItem_ClickText2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  削除失敗 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property DeleteStripMenuItem_ClickText3() As String
            Get
                Return ResourceManager.GetString("DeleteStripMenuItem_ClickText3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  削除成功 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property DeleteStripMenuItem_ClickText4() As String
            Get
                Return ResourceManager.GetString("DeleteStripMenuItem_ClickText4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  更新間隔には数値（0または15～6000）を指定してください。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property DMPeriod_ValidatingText1() As String
            Get
                Return ResourceManager.GetString("DMPeriod_ValidatingText1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  更新間隔には数値（0または15～6000）を指定してください。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property DMPeriod_ValidatingText2() As String
            Get
                Return ResourceManager.GetString("DMPeriod_ValidatingText2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  正規表現パターンが間違っています。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property DoTabSearchText1() As String
            Get
                Return ResourceManager.GetString("DoTabSearchText1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  検索条件に一致するデータは見つかりません。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property DoTabSearchText2() As String
            Get
                Return ResourceManager.GetString("DoTabSearchText2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  検索 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property DoTabSearchText3() As String
            Get
                Return ResourceManager.GetString("DoTabSearchText3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  選択された発言をFavoritesに追加します。よろしいですか？ に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property FavAddToolStripMenuItem_ClickText1() As String
            Get
                Return ResourceManager.GetString("FavAddToolStripMenuItem_ClickText1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Fav確認 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property FavAddToolStripMenuItem_ClickText2() As String
            Get
                Return ResourceManager.GetString("FavAddToolStripMenuItem_ClickText2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Fav追加中... に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property FavAddToolStripMenuItem_ClickText3() As String
            Get
                Return ResourceManager.GetString("FavAddToolStripMenuItem_ClickText3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Fav追加なし に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property FavAddToolStripMenuItem_ClickText4() As String
            Get
                Return ResourceManager.GetString("FavAddToolStripMenuItem_ClickText4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  選択された発言をFavoritesから削除します。よろしいですか？ に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property FavRemoveToolStripMenuItem_ClickText1() As String
            Get
                Return ResourceManager.GetString("FavRemoveToolStripMenuItem_ClickText1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Fav確認 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property FavRemoveToolStripMenuItem_ClickText2() As String
            Get
                Return ResourceManager.GetString("FavRemoveToolStripMenuItem_ClickText2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Fav削除中... に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property FavRemoveToolStripMenuItem_ClickText3() As String
            Get
                Return ResourceManager.GetString("FavRemoveToolStripMenuItem_ClickText3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Fav削除なし に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property FavRemoveToolStripMenuItem_ClickText4() As String
            Get
                Return ResourceManager.GetString("FavRemoveToolStripMenuItem_ClickText4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  更新中... に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property Form1_LoadText1() As String
            Get
                Return ResourceManager.GetString("Form1_LoadText1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  idを入力して下さい。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property FRMessage1() As String
            Get
                Return ResourceManager.GetString("FRMessage1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  失敗 :  に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property FRMessage2() As String
            Get
                Return ResourceManager.GetString("FRMessage2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  完了！ に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property FRMessage3() As String
            Get
                Return ResourceManager.GetString("FRMessage3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  &gt;&gt;&gt; ◯ フォローしています に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property GetFriendshipInfo1() As String
            Get
                Return ResourceManager.GetString("GetFriendshipInfo1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  &gt;&gt;&gt; × フォローしていません に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property GetFriendshipInfo2() As String
            Get
                Return ResourceManager.GetString("GetFriendshipInfo2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  &lt;&lt;&lt; ◯ フォローされています に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property GetFriendshipInfo3() As String
            Get
                Return ResourceManager.GetString("GetFriendshipInfo3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  &lt;&lt;&lt; × フォローされていません に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property GetFriendshipInfo4() As String
            Get
                Return ResourceManager.GetString("GetFriendshipInfo4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''   さんとのフォロー関係 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property GetFriendshipInfo5() As String
            Get
                Return ResourceManager.GetString("GetFriendshipInfo5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  フォロー状況取得失敗 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property GetFriendshipInfo6() As String
            Get
                Return ResourceManager.GetString("GetFriendshipInfo6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recent更新完了 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property GetTimelineWorker_RunWorkerCompletedText1() As String
            Get
                Return ResourceManager.GetString("GetTimelineWorker_RunWorkerCompletedText1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  起動時読込完了 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property GetTimelineWorker_RunWorkerCompletedText10() As String
            Get
                Return ResourceManager.GetString("GetTimelineWorker_RunWorkerCompletedText10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  DMRcv更新完了 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property GetTimelineWorker_RunWorkerCompletedText11() As String
            Get
                Return ResourceManager.GetString("GetTimelineWorker_RunWorkerCompletedText11", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  DMSnt更新中... に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property GetTimelineWorker_RunWorkerCompletedText12() As String
            Get
                Return ResourceManager.GetString("GetTimelineWorker_RunWorkerCompletedText12", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  DMSnt更新完了 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property GetTimelineWorker_RunWorkerCompletedText13() As String
            Get
                Return ResourceManager.GetString("GetTimelineWorker_RunWorkerCompletedText13", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  POST完了 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property GetTimelineWorker_RunWorkerCompletedText14() As String
            Get
                Return ResourceManager.GetString("GetTimelineWorker_RunWorkerCompletedText14", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Fav追加( に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property GetTimelineWorker_RunWorkerCompletedText15() As String
            Get
                Return ResourceManager.GetString("GetTimelineWorker_RunWorkerCompletedText15", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  BlackFav追加( に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property GetTimelineWorker_RunWorkerCompletedText15_black() As String
            Get
                Return ResourceManager.GetString("GetTimelineWorker_RunWorkerCompletedText15_black", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  ) 失敗: に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property GetTimelineWorker_RunWorkerCompletedText16() As String
            Get
                Return ResourceManager.GetString("GetTimelineWorker_RunWorkerCompletedText16", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Fav削除( に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property GetTimelineWorker_RunWorkerCompletedText17() As String
            Get
                Return ResourceManager.GetString("GetTimelineWorker_RunWorkerCompletedText17", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  ) 失敗: に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property GetTimelineWorker_RunWorkerCompletedText18() As String
            Get
                Return ResourceManager.GetString("GetTimelineWorker_RunWorkerCompletedText18", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Fav取得中... に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property GetTimelineWorker_RunWorkerCompletedText19() As String
            Get
                Return ResourceManager.GetString("GetTimelineWorker_RunWorkerCompletedText19", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''   ポストまで読み込み完了。さらに読み込みますか？ に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property GetTimelineWorker_RunWorkerCompletedText2() As String
            Get
                Return ResourceManager.GetString("GetTimelineWorker_RunWorkerCompletedText2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Fav取得完了 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property GetTimelineWorker_RunWorkerCompletedText20() As String
            Get
                Return ResourceManager.GetString("GetTimelineWorker_RunWorkerCompletedText20", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  読み込み継続確認 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property GetTimelineWorker_RunWorkerCompletedText3() As String
            Get
                Return ResourceManager.GetString("GetTimelineWorker_RunWorkerCompletedText3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Reply更新中... に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property GetTimelineWorker_RunWorkerCompletedText4() As String
            Get
                Return ResourceManager.GetString("GetTimelineWorker_RunWorkerCompletedText4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recent更新中... に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property GetTimelineWorker_RunWorkerCompletedText5() As String
            Get
                Return ResourceManager.GetString("GetTimelineWorker_RunWorkerCompletedText5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  pages に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property GetTimelineWorker_RunWorkerCompletedText6() As String
            Get
                Return ResourceManager.GetString("GetTimelineWorker_RunWorkerCompletedText6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  DMRcv更新中... に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property GetTimelineWorker_RunWorkerCompletedText8() As String
            Get
                Return ResourceManager.GetString("GetTimelineWorker_RunWorkerCompletedText8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Reply更新完了 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property GetTimelineWorker_RunWorkerCompletedText9() As String
            Get
                Return ResourceManager.GetString("GetTimelineWorker_RunWorkerCompletedText9", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  (新規タブ) に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDRuleMenuItem_ClickText1() As String
            Get
                Return ResourceManager.GetString("IDRuleMenuItem_ClickText1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  タブ　&quot;&quot;{0}&quot;&quot;　は既に存在するため、追加できません。別の名前を指定してください。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDRuleMenuItem_ClickText2() As String
            Get
                Return ResourceManager.GetString("IDRuleMenuItem_ClickText2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  タブ追加 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDRuleMenuItem_ClickText3() As String
            Get
                Return ResourceManager.GetString("IDRuleMenuItem_ClickText3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recentに残しますか？{0}  「はい」　：残す{0}  「いいえ」：残さない に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDRuleMenuItem_ClickText4() As String
            Get
                Return ResourceManager.GetString("IDRuleMenuItem_ClickText4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  移動確認 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDRuleMenuItem_ClickText5() As String
            Get
                Return ResourceManager.GetString("IDRuleMenuItem_ClickText5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  マークをつけますか？{0}  「はい」　：つける{0}  「いいえ」：つけない に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDRuleMenuItem_ClickText6() As String
            Get
                Return ResourceManager.GetString("IDRuleMenuItem_ClickText6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  マーク確認 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDRuleMenuItem_ClickText7() As String
            Get
                Return ResourceManager.GetString("IDRuleMenuItem_ClickText7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Twitterからのお知らせはありません。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property InfoTwitterMenuItem_ClickText1() As String
            Get
                Return ResourceManager.GetString("InfoTwitterMenuItem_ClickText1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Twitterからのお知らせ に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property InfoTwitterMenuItem_ClickText2() As String
            Get
                Return ResourceManager.GetString("InfoTwitterMenuItem_ClickText2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  タイムライン振り分け に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property InputTabName_Load1() As String
            Get
                Return ResourceManager.GetString("InputTabName_Load1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  この設定ファイルは Tween により自動生成されました。手動で変更しないでください。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property LoadConfigurationText1() As String
            Get
                Return ResourceManager.GetString("LoadConfigurationText1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  正規表現パターンが間違っています。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property MenuItemSearchNext_ClickText1() As String
            Get
                Return ResourceManager.GetString("MenuItemSearchNext_ClickText1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  検索条件に一致するデータは見つかりません。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property MenuItemSearchNext_ClickText2() As String
            Get
                Return ResourceManager.GetString("MenuItemSearchNext_ClickText2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  検索 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property MenuItemSearchNext_ClickText3() As String
            Get
                Return ResourceManager.GetString("MenuItemSearchNext_ClickText3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  正規表現パターンが間違っています。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property MenuItemSearchPrev_ClickText1() As String
            Get
                Return ResourceManager.GetString("MenuItemSearchPrev_ClickText1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  検索条件に一致するデータは見つかりません。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property MenuItemSearchPrev_ClickText2() As String
            Get
                Return ResourceManager.GetString("MenuItemSearchPrev_ClickText2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  検索 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property MenuItemSearchPrev_ClickText3() As String
            Get
                Return ResourceManager.GetString("MenuItemSearchPrev_ClickText3", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property MIcon() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("MIcon", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  ページ数には数値（1～20）を指定してください。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property NextPages_ValidatingText1() As String
            Get
                Return ResourceManager.GetString("NextPages_ValidatingText1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  ページ数には数値（1～20）を指定してください。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property NextPages_ValidatingText2() As String
            Get
                Return ResourceManager.GetString("NextPages_ValidatingText2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  閾値には数値（1～20）を指定してください。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property NextThreshold_ValidatingText1() As String
            Get
                Return ResourceManager.GetString("NextThreshold_ValidatingText1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  閾値には数値（1～20）を指定してください。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property NextThreshold_ValidatingText2() As String
            Get
                Return ResourceManager.GetString("NextThreshold_ValidatingText2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  いいえ に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property No() As String
            Get
                Return ResourceManager.GetString("No", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  140文字を越えています。URL短縮、フッタ除去、末尾カットを行って投稿しますか？ に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property PostLengthOverMessage1() As String
            Get
                Return ResourceManager.GetString("PostLengthOverMessage1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  文字数制限オーバー に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property PostLengthOverMessage2() As String
            Get
                Return ResourceManager.GetString("PostLengthOverMessage2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  POST完了 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property PostWorker_RunWorkerCompletedText4() As String
            Get
                Return ResourceManager.GetString("PostWorker_RunWorkerCompletedText4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recent更新中... に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property PostWorker_RunWorkerCompletedText5() As String
            Get
                Return ResourceManager.GetString("PostWorker_RunWorkerCompletedText5", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Refresh() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Refresh", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property Refresh2() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Refresh2", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property Refresh3() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Refresh3", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property Refresh4() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Refresh4", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  新着 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property RefreshDirectMessageText1() As String
            Get
                Return ResourceManager.GetString("RefreshDirectMessageText1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  件 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property RefreshDirectMessageText2() As String
            Get
                Return ResourceManager.GetString("RefreshDirectMessageText2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recent更新中... に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property RefreshStripMenuItem_ClickText1() As String
            Get
                Return ResourceManager.GetString("RefreshStripMenuItem_ClickText1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Reply更新中... に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property RefreshStripMenuItem_ClickText2() As String
            Get
                Return ResourceManager.GetString("RefreshStripMenuItem_ClickText2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  DMRcv更新中... に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property RefreshStripMenuItem_ClickText3() As String
            Get
                Return ResourceManager.GetString("RefreshStripMenuItem_ClickText3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  新着 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property RefreshTimelineText1() As String
            Get
                Return ResourceManager.GetString("RefreshTimelineText1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  件 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property RefreshTimelineText2() As String
            Get
                Return ResourceManager.GetString("RefreshTimelineText2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  ログ読込 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property RefreshTimelineText3() As String
            Get
                Return ResourceManager.GetString("RefreshTimelineText3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  起動読込 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property RefreshTimelineText4() As String
            Get
                Return ResourceManager.GetString("RefreshTimelineText4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  このタブを削除してもよろしいですか？{0} に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property RemoveSpecifiedTabText1() As String
            Get
                Return ResourceManager.GetString("RemoveSpecifiedTabText1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  タブの削除確認 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property RemoveSpecifiedTabText2() As String
            Get
                Return ResourceManager.GetString("RemoveSpecifiedTabText2", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Reply() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Reply", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property ReplyBlink() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ReplyBlink", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Retweetしてもよろしいですか？ に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property RetweetQuestion1() As String
            Get
                Return ResourceManager.GetString("RetweetQuestion1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  ユーザー名とパスワードを指定してください。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property Save_ClickText1() As String
            Get
                Return ResourceManager.GetString("Save_ClickText1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  ユーザー名に『@』を含めないでください。（メールアドレス不可） に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property Save_ClickText2() As String
            Get
                Return ResourceManager.GetString("Save_ClickText2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  設定値に誤りがあります。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property Save_ClickText3() As String
            Get
                Return ResourceManager.GetString("Save_ClickText3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  選択中タブの全発言を保存しますか？{0}　「はい」　　　：全発言を保存する{0}　「いいえ」　　：選択している発言のみ保存する{0}　「キャンセル」：保存処理をキャンセル{0}（タブ区切りのテキストファイル形式で保存します） に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property SaveLogMenuItem_ClickText1() As String
            Get
                Return ResourceManager.GetString("SaveLogMenuItem_ClickText1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  保存対象選択 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property SaveLogMenuItem_ClickText2() As String
            Get
                Return ResourceManager.GetString("SaveLogMenuItem_ClickText2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  TSVファイル(*.tsv)|*.tsv|すべてのファイル(*.*)|*.* に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property SaveLogMenuItem_ClickText3() As String
            Get
                Return ResourceManager.GetString("SaveLogMenuItem_ClickText3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  保存先のファイルを選択してください に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property SaveLogMenuItem_ClickText4() As String
            Get
                Return ResourceManager.GetString("SaveLogMenuItem_ClickText4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  http://ja.wikipedia.org/wiki/{0} に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property SearchItem1Url() As String
            Get
                Return ResourceManager.GetString("SearchItem1Url", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  http://www.google.com/search?hl=ja&amp;q={0} に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property SearchItem2Url() As String
            Get
                Return ResourceManager.GetString("SearchItem2Url", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  http://pcod.no-ip.org/yats/search?query={0} に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property SearchItem3Url() As String
            Get
                Return ResourceManager.GetString("SearchItem3Url", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  http://search.twitter.com/search?q={0} に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property SearchItem4Url() As String
            Get
                Return ResourceManager.GetString("SearchItem4Url", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  [ユーザ･･･{0}]   に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property SetFiltersText1() As String
            Get
                Return ResourceManager.GetString("SetFiltersText1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  マークする に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property SetFiltersText10() As String
            Get
                Return ResourceManager.GetString("SetFiltersText10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  コピーする/ に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property SetFiltersText11() As String
            Get
                Return ResourceManager.GetString("SetFiltersText11", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''   &lt;&lt;除外&gt;&gt;  に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property SetFiltersText12() As String
            Get
                Return ResourceManager.GetString("SetFiltersText12", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  大小区別/ に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property SetFiltersText13() As String
            Get
                Return ResourceManager.GetString("SetFiltersText13", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  [ユーザ･･･(全て)]   に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property SetFiltersText2() As String
            Get
                Return ResourceManager.GetString("SetFiltersText2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  [本文･･･ に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property SetFiltersText3() As String
            Get
                Return ResourceManager.GetString("SetFiltersText3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  ]   に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property SetFiltersText4() As String
            Get
                Return ResourceManager.GetString("SetFiltersText4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  複合/ に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property SetFiltersText5() As String
            Get
                Return ResourceManager.GetString("SetFiltersText5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  単一/ に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property SetFiltersText6() As String
            Get
                Return ResourceManager.GetString("SetFiltersText6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Regexp/ に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property SetFiltersText7() As String
            Get
                Return ResourceManager.GetString("SetFiltersText7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  URL/ に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property SetFiltersText8() As String
            Get
                Return ResourceManager.GetString("SetFiltersText8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  移動する に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property SetFiltersText9() As String
            Get
                Return ResourceManager.GetString("SetFiltersText9", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  {0}件 (未読＠) に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property SetMainWindowTitleText1() As String
            Get
                Return ResourceManager.GetString("SetMainWindowTitleText1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  {0}件 (未読) に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property SetMainWindowTitleText2() As String
            Get
                Return ResourceManager.GetString("SetMainWindowTitleText2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  {0} ({1})件 (未読) に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property SetMainWindowTitleText3() As String
            Get
                Return ResourceManager.GetString("SetMainWindowTitleText3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  {0}/{1}件 (未読/総件数) に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property SetMainWindowTitleText4() As String
            Get
                Return ResourceManager.GetString("SetMainWindowTitleText4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  [タブ: {0}/{1} 全体: {2}/{3} (返信: {4})] [時速: 投 {5}/ ☆ {6}/ 流 {7}] [間隔:  に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property SetStatusLabelText1() As String
            Get
                Return ResourceManager.GetString("SetStatusLabelText1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  -] に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property SetStatusLabelText2() As String
            Get
                Return ResourceManager.GetString("SetStatusLabelText2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  ] に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property SetStatusLabelText3() As String
            Get
                Return ResourceManager.GetString("SetStatusLabelText3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  ユーザー名とパスワードを入力して「認証する」ボタンを押してください。認証せずに終了してもよろしいですか？ に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property Setting_FormClosing1() As String
            Get
                Return ResourceManager.GetString("Setting_FormClosing1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  ユーザー情報解析失敗 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ShowUserInfo1() As String
            Get
                Return ResourceManager.GetString("ShowUserInfo1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  まだあなたのプロフィール情報を取得していません。投稿後に再度お試しください。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ShowYourProfileText1() As String
            Get
                Return ResourceManager.GetString("ShowYourProfileText1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  読み込みページ数には数値（1～999）を指定してください。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property StartupReadDM_ValidatingText1() As String
            Get
                Return ResourceManager.GetString("StartupReadDM_ValidatingText1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  読み込みページ数には数値（1～999）を指定してください。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property StartupReadDM_ValidatingText2() As String
            Get
                Return ResourceManager.GetString("StartupReadDM_ValidatingText2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  読み込みページ数には数値（1～999）を指定してください。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property StartupReadPages_ValidatingText1() As String
            Get
                Return ResourceManager.GetString("StartupReadPages_ValidatingText1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  読み込みページ数には数値（1～999）を指定してください。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property StartupReadPages_ValidatingText2() As String
            Get
                Return ResourceManager.GetString("StartupReadPages_ValidatingText2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  読み込みページ数には数値（0～999）を指定してください。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property StartupReadReply_ValidatingText1() As String
            Get
                Return ResourceManager.GetString("StartupReadReply_ValidatingText1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  読み込みページ数には数値（0～999）を指定してください。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property StartupReadReply_ValidatingText2() As String
            Get
                Return ResourceManager.GetString("StartupReadReply_ValidatingText2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Tweenは既に起動されています。2重起動する場合は、別フォルダのTween.exeを実行してください。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property StartupText1() As String
            Get
                Return ResourceManager.GetString("StartupText1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Tween二重起動チェック に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property StartupText2() As String
            Get
                Return ResourceManager.GetString("StartupText2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  投稿に失敗しました に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property StatusUpdateFailed1() As String
            Get
                Return ResourceManager.GetString("StatusUpdateFailed1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  もう一度投稿を試みますか？ に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property StatusUpdateFailed2() As String
            Get
                Return ResourceManager.GetString("StatusUpdateFailed2", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property TabIcon() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("TabIcon", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  (新規タブ) に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property TabMenuItem_ClickText1() As String
            Get
                Return ResourceManager.GetString("TabMenuItem_ClickText1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  タブ　&quot;&quot;{0}&quot;&quot;　は既に存在するため、追加できません。別の名前を指定してください。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property TabMenuItem_ClickText2() As String
            Get
                Return ResourceManager.GetString("TabMenuItem_ClickText2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  タブ追加 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property TabMenuItem_ClickText3() As String
            Get
                Return ResourceManager.GetString("TabMenuItem_ClickText3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  タブ　&quot;&quot;{0}&quot;&quot;　は既に存在するため、変更できません。別の名前を指定してください。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property Tabs_DoubleClickText1() As String
            Get
                Return ResourceManager.GetString("Tabs_DoubleClickText1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  タブ名変更 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property Tabs_DoubleClickText2() As String
            Get
                Return ResourceManager.GetString("Tabs_DoubleClickText2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  復活の呪文を指定してください。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property TextBoxOutputzKey_Validating() As String
            Get
                Return ResourceManager.GetString("TextBoxOutputzKey_Validating", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  取得発言数は20～200件を指定してください。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property TextCountApi_Validating1() As String
            Get
                Return ResourceManager.GetString("TextCountApi_Validating1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  ポート番号には整数値を指定してください。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property TextProxyPort_ValidatingText1() As String
            Get
                Return ResourceManager.GetString("TextProxyPort_ValidatingText1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  ポート番号には0～65535を指定してください。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property TextProxyPort_ValidatingText2() As String
            Get
                Return ResourceManager.GetString("TextProxyPort_ValidatingText2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  更新間隔には数値（0または15～6000）を指定してください。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property TimelinePeriod_ValidatingText1() As String
            Get
                Return ResourceManager.GetString("TimelinePeriod_ValidatingText1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  更新間隔には数値（0または15～6000）を指定してください。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property TimelinePeriod_ValidatingText2() As String
            Get
                Return ResourceManager.GetString("TimelinePeriod_ValidatingText2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  DMRcv更新中... に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property TimerDM_TickText1() As String
            Get
                Return ResourceManager.GetString("TimerDM_TickText1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recent更新中... に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property TimerTimeline_TickText1() As String
            Get
                Return ResourceManager.GetString("TimerTimeline_TickText1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  このファイルの内容を kiri_feather@users.sourceforge.jp まで送っていただけると助かります。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property TraceOutText1() As String
            Get
                Return ResourceManager.GetString("TraceOutText1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  ご面倒なら@kiri_featherまでお知らせ頂くだけでも助かります。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property TraceOutText2() As String
            Get
                Return ResourceManager.GetString("TraceOutText2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  動作環境: に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property TraceOutText3() As String
            Get
                Return ResourceManager.GetString("TraceOutText3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''     オペレーティング システム: {0} に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property TraceOutText4() As String
            Get
                Return ResourceManager.GetString("TraceOutText4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''     共通言語ランタイム          : {0} に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property TraceOutText5() As String
            Get
                Return ResourceManager.GetString("TraceOutText5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''     Tween.exeのバージョン    : {0} に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property TraceOutText6() As String
            Get
                Return ResourceManager.GetString("TraceOutText6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  {0} のバージョン情報 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property TweenAboutBox_LoadText1() As String
            Get
                Return ResourceManager.GetString("TweenAboutBox_LoadText1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  バージョン {0} に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property TweenAboutBox_LoadText2() As String
            Get
                Return ResourceManager.GetString("TweenAboutBox_LoadText2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  **** エラー ログ: {0} **** に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property UnhandledExceptionText1() As String
            Get
                Return ResourceManager.GetString("UnhandledExceptionText1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  エラー発生 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property UnhandledExceptionText10() As String
            Get
                Return ResourceManager.GetString("UnhandledExceptionText10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Administrator権限： に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property UnhandledExceptionText11() As String
            Get
                Return ResourceManager.GetString("UnhandledExceptionText11", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Users権限： に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property UnhandledExceptionText12() As String
            Get
                Return ResourceManager.GetString("UnhandledExceptionText12", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  このファイルの内容を kiri_feather@users.sourceforge.jp まで送っていただけると助かります。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property UnhandledExceptionText2() As String
            Get
                Return ResourceManager.GetString("UnhandledExceptionText2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  ご面倒なら@kiri_featherまでお知らせ頂くだけでも助かります。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property UnhandledExceptionText3() As String
            Get
                Return ResourceManager.GetString("UnhandledExceptionText3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  動作環境: に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property UnhandledExceptionText4() As String
            Get
                Return ResourceManager.GetString("UnhandledExceptionText4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''     オペレーティング システム: {0} に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property UnhandledExceptionText5() As String
            Get
                Return ResourceManager.GetString("UnhandledExceptionText5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''     共通言語ランタイム          : {0} に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property UnhandledExceptionText6() As String
            Get
                Return ResourceManager.GetString("UnhandledExceptionText6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''     Tween.exeのバージョン    : {0} に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property UnhandledExceptionText7() As String
            Get
                Return ResourceManager.GetString("UnhandledExceptionText7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  例外 {0}: {1} に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property UnhandledExceptionText8() As String
            Get
                Return ResourceManager.GetString("UnhandledExceptionText8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  エラーが発生しました。ごめんなさい。ログをexeファイルのある場所に {0} として作ったので、kiri_feather@users.sourceforge.jpまで送っていただけると助かります。{1}ご面倒なら@kiri_featherまでお知らせ頂くだけでも助かります。{1}「はい」ボタンをクリックするとログを開きます。ログを開かない場合は「いいえ」、このまま終了する場合は「キャンセル」ボタンをクリックしてください。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property UnhandledExceptionText9() As String
            Get
                Return ResourceManager.GetString("UnhandledExceptionText9", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Followers取得中... に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property UpdateFollowersMenuItem1_ClickText1() As String
            Get
                Return ResourceManager.GetString("UpdateFollowersMenuItem1_ClickText1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Followers取得エラー： に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property UpdateFollowersMenuItem1_ClickText2() As String
            Get
                Return ResourceManager.GetString("UpdateFollowersMenuItem1_ClickText2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Followers取得完了 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property UpdateFollowersMenuItem1_ClickText3() As String
            Get
                Return ResourceManager.GetString("UpdateFollowersMenuItem1_ClickText3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  はい に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property Yes() As String
            Get
                Return ResourceManager.GetString("Yes", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
